### ISSUE TITLE
run-length-encoder top-level

### ISSUE THREAD

**Issue by cfelton** [cfelton/test_jpeg#21]
@Vikram9866 

The run-length-encoder (rle) currently has the following interface (ports and parameters)

```python
def rletop(dfifo_const, constants, reset, clock,
                indatastream, bufferdatabus, rleconfig):
```

The typical `block` argument pattern is `myblock(*ports, **parameters)`.  In this case the parameters where organized into an object.  Couple problems with this, calling them constants is a little misleading (a little nuance here) they are parameters to the core/subblock.

The subblocks should have a pattern like

```python
def rle(clock, reset, indata, bufferdata, rleconfig, )
```

We need to be consistent in the subblocks, we can have `clock` and `reset` at the beginning or the end of the portlist either is fine but we should be consistent in all ~~modules~~ blocks.  

Some of the parameters currently sent to the `rle` are redundant, example, the `data_width` can be extracted from the other ports a user should not need to define this twice.  Some care needs to be applied to determine the critical domain level parameters for the blocks and the other derived constants.  
Also, these parameters need to be documented in the docstring.

cc: @mkatsimpris

**Comment by Vikram9866** [comment]
Yes, I understand that. I will change it.

**Comment by cfelton** [comment]
@Vikram9866, I am going to create a PR shortly with some reorg.  I didn't change the interfaces in the code in this PR but I did change things related, they will all need to be updated and changed.

**Comment by mkatsimpris** [comment]
Nice @cfelton  I will change my code accordingly. I am waiting for the reorg branch, in order to change my code in zig-zag module.
Thanks

**Comment by Vikram9866** [comment]
@cfelton  .. I have gone through the reorg branch ... I will finish the interface work once you make a PR.
