### ISSUE TITLE
Block Buffer 

### ISSUE THREAD

**Issue by mkatsimpris** [cfelton/test_jpeg#37]
@cfelton  Can we start a discussion about the design of the block buffer?

**Comment by mkatsimpris** [comment]
My first thought is to use 8 rams. Each ram will store a line of the image. When all the rams are full and the frontend hasn't processed all the blocks the inputs should halt.

**Comment by cfelton** [comment]
@mkatsimpris why specify N (8) RAMs?  Shouldn't it simply be a buffer of size N that takes a single pixel in at some rate (dependent on the resolution, block size, refresh rate) and outputs a block?

We don't need to store the same block in different RAMS but simply reread the block, the buffer needs a control that says `next_block` or something, this might be organized as a FIFO and a RAM but I am not following why more than that would be needed?

**Comment by cfelton** [comment]
@mkatsimpris, your original description defines a RAM for each row?  Is each RAM large enough to hold two rows?

**Comment by mkatsimpris** [comment]
@cfelton the video source outputs serially each row of the image right? 

I have a buffer which can store 8 rows. Each row has some columns which depends one the image width. I dont store each block 3 times, I just output it 3 times. When the buffer has stored 8 rows and 8 columns it starts to output the block.

**Comment by mkatsimpris** [comment]
In order for the video source to input data without stop i use a module with 3 of the buffers. So the read and write of data isnt overlapping
